version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/code/app
      - exclude:/code/app/node_modules
    networks:
      - web
    command: yarn start

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/code/app
    networks:
      - web
    ports:
      - "3001:3001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 3001

  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    networks:
      - web
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    container_name: grafana
    build:
      context: ./grafana
      dockerfile: Dockerfile
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - web
    ports:
      - "9000:3000"
    command: yarn start

  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    networks:
      - web
    depends_on:
      - prometheus
      - grafana
      - backend
      - frontend
    ports:
      - "8000:8000"

networks:
  web:

volumes:
  exclude:
  grafana-data:
  prometheus-data:
